### ISSUE TITLE
Default Eclipse broker has changed

### ISSUE THREAD

**Issue by andypiper** [AnaviTechnology/anavi-thermometer-sw#46]
By default, the thermometer sketch / wifi configuration page attempts to send MQTT messages via iot.eclipse.org, which does not work.

The current sandbox MQTT broker for Eclipse is mqtt.eclipseprojects.io

~~(also, where is the code for the web config page - is that run separately from the ESP flashed sketch?)~~
figured this ^^ out, it is from WifiManager

**Comment by leon-anavi** [comment]
Hi @andypiper,

Thank you for reporting this issue.

The default URL for the MQTT broker is hard-coded here: https://github.com/AnaviTechnology/anavi-thermometer-sw/blob/master/anavi-thermometer-sw/anavi-thermometer-sw.ino#L366

Btw the HTML5 demo page is also available in GitHub: https://github.com/AnaviTechnology/anavi-light-demo

Thanks,
Leon
